### ISSUE TITLE
Create a contact using Python

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#11]
Code sample to create a contact using Nylas Python SDK.

**Comment by SouvikDcoder** [comment]
Hey @relaxedtomato Please assign the issue to me. I would like to contribute to this.

**Comment by relaxedtomato** [comment]
@SouvikDcoder  - Let's tackle a single issue per [PR](https://github.com/nylas-samples/nylas-hacktoberfest-2022/pull/47). So this is for creating a contact. Update your existing PR.
