### ISSUE TITLE
Read contacts using Python

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#12]
Code sample to read contacts using Nylas Python SDK.

**Comment by Divyessh** [comment]
I hope this PR meets the contribution requirements and guidelines. If there is a requirement for any modification, please let me know.
Thanks!

**Comment by relaxedtomato** [comment]
Thanks for jumping in @Divyessh.

**Comment by Divyessh** [comment]
@relaxedtomato I have already opened the PR, please check it out, and if matches the requirements, please merge it.
Thanks!

PR -> #45

**Comment by relaxedtomato** [comment]
Hi @Divyessh - will take a look shortly. Few comments to address:

1. I noticed your PR has multiple issues, can we separate [create_email_label](https://github.com/nylas-samples/nylas-hacktoberfest-2022/pull/45/commits/14c499000dcbb467bfc053daeb6c74b0098bc880) into a separate PR. 
2. Also, I see you didn't ask to take on [this issue](https://github.com/nylas-samples/nylas-hacktoberfest-2022/issues/32).

**Comment by Divyessh** [comment]
Hey @relaxedtomato 
Thank you for the heads up. I have reverted the last commit and added the readme file for the script. Please review it once.
