### ISSUE TITLE
Update a contact using Java

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#21]
Code sample to update a contact using Nylas Java SDK.

**Comment by NikhilTaneja98** [comment]
@relaxedtomato Can you please assign this to me. I am ready to contribute on this task.

**Comment by relaxedtomato** [comment]
Hi @NikhilTaneja98 - sure, please have a read of our [readme](https://github.com/nylas-samples/nylas-hacktoberfest-2022) and clarify any questions you may have.

**Comment by NikhilTaneja98** [comment]
We will provide the contact id with the updated contact object?

**Comment by NikhilTaneja98** [comment]
Hi @relaxedtomato, I think this issue should be linked with #54 PR. Do I need to add anything from my side?

**Comment by atejada** [comment]
Merged and issue closed
