### ISSUE TITLE
Create a Calendar using Java

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#38]
Code sample to create a calendar using Nylas Java SDK.

**Comment by itsvipindev** [comment]
i can make a calculator with java which can multiply divide add subtract

**Comment by relaxedtomato** [comment]
Hi @itsvipindev - we are looking for a code sample to create a Calendar. Have a look at our [learning resources](https://github.com/nylas-samples/nylas-hacktoberfest-2022#other-places-to-learn) to see if this is something you like to take on.

**Comment by yagyeshbagaya** [comment]
@relaxedtomato Please assign this issue to me ...
Thanks

**Comment by atejada** [comment]
@yagyeshbagaya You're requesting multiple issues. Focus on solving one, then request another one 😃 Which one would you like? You are requesting #15 #26 and #38

**Comment by yagyeshbagaya** [comment]
@atejada assign me #38

**Comment by atejada** [comment]
Ok @yagyeshbagaya you got it 😉

**Comment by yagyeshbagaya** [comment]
@atejada Calendar Created Sucessfully

**Comment by atejada** [comment]
@yagyeshbagaya Let me review it today...at a glance it looks great 👍
