### ISSUE TITLE
Using the Nylas Java SDK, list last 10 emails that contain a keyword, like 'unsubscribe'

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#65]
Using the Nylas Java SDK, list last 10 emails that contain a keyword, like 'unsubscribe'

**Comment by isanketsaha** [comment]
@relaxedtomato assign this to me.

**Comment by atejada** [comment]
@isanketsaha Done 😉

**Comment by isanketsaha** [comment]
@atejada , changes done. please review #100

**Comment by atejada** [comment]
Thanks for your contributions @isanketsaha 😄 Another issue closed 😉
