### ISSUE TITLE
Using the Nylas Java SDK, list last 10 calendar events that contain a keyword, like 'coffee'

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#81]
Using the Nylas Java SDK, list last 10 calendar events that contain a keyword, like 'coffee'

**Comment by isanketsaha** [comment]
@relaxedtomato , please assign this to me.

**Comment by atejada** [comment]
@isanketsaha There you go 😄

**Comment by isanketsaha** [comment]
I have two questions. 
1. Calender and events are two different types of objects. So for this issue should I perform the operation on the calendar or event?
2. the search keyword should I be searching in the description or title or both?

@atejada  @relaxedtomato

**Comment by atejada** [comment]
@isanketsaha You need to pick a Calendar first, then search on the events that have the keyword, for example, "coffee" and display them. Where would you search? It depends on you 😄 Although the title should be enough.

**Comment by isanketsaha** [comment]
@atejada, can you please review my PR. #99

**Comment by atejada** [comment]
Merged and issue closed.
