### ISSUE TITLE
Using the Nylas Python SDK, list last 10 calendar events that contain a keyword, like 'coffee'

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2022#82]
Using the Nylas Python SDK, list last 10 calendar events that contain a keyword, like 'coffee'

**Comment by SouvikDcoder** [comment]
@relaxedtomato @atejada Can I work on this please 😃

**Comment by atejada** [comment]
Sure you can 😉
